server {
    listen 80;
    server_name localhost;

    # 1. Раздача статических файлов фронтенда (Vite)
    location / {
        root /usr/share/nginx/html;
        # Указываем auth.html как главный стартовый файл
        index auth.html; 
        
        # Если пользователь введет адрес страницы, которой нет на диске,
        # Nginx перенаправит его на стартовый auth.html
        try_files $uri $uri/ /auth.html; 
    }

    # 2. Проксирование запросов к бэкенду
    location /api/ {
        proxy_pass http://web_app:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
