"""add_unique_constraint_to_words_info

Revision ID: 535cfcf81d9b
Revises: 8d1bf371e74c
Create Date: 2026-07-07 13:14:38.023162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '535cfcf81d9b'
down_revision: Union[str, Sequence[str], None] = '8d1bf371e74c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('words_info_origin_key'), 'words_info', type_='unique')
    op.create_unique_constraint('origin_translation_unique', 'words_info', ['origin', 'translation'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('origin_translation_unique', 'words_info', type_='unique')
    op.create_unique_constraint(op.f('words_info_origin_key'), 'words_info', ['origin'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
